add_subdirectory(${MSE_BASE_SOURCE_DIR}/examples/dungeontris)
# add_subdirectory(${MSE_BASE_SOURCE_DIR}/examples/lesta-autobattler)
# add_subdirectory(${MSE_BASE_SOURCE_DIR}/examples/chalkboard)
# add_subdirectory(${MSE_BASE_SOURCE_DIR}/examples/proto-snake)
# add_subdirectory(${MSE_BASE_SOURCE_DIR}/examples/sandbox)
# add_subdirectory(${MSE_BASE_SOURCE_DIR}/examples/gui-simple)
# add_subdirectory(${MSE_BASE_SOURCE_DIR}/examples/card-game)
